### ISSUE TITLE
Lacks a great maintainer

### ISSUE THREAD

**Issue by C0DK** [Unge-Programmoerer/Grubbe-framework#21]
I'm submitting a ...

 bug report
 feature request

What is the current behavior?

I feel like the project isn't maintained ENOUGH. it is maintained to some extend, and greatly to that extend, but it is lacking something

What is the expected behavior?

It would just be better for all people involved if i was a maintainer tbh.

Please tell us about your environment:

Version: 2.0.0-beta.2
Browser: [all ]
Language: [English, Danish, Python, Javascript, PHP, GruPHP, Love, Go]
Other information see attached [linkedin](https://www.linkedin.com/in/thecdk/)

**Comment by olidotjpeg** [comment]
Closing this as this is super toxic. It's ultra maintained, 0 bugs.
