### ISSUE TITLE
Invalid package name

### ISSUE THREAD

**Issue by boserup** [Unge-Programmoerer/Grubbe-framework#3]
The package name 'Unge-Programmoerer/Grubbe-framework' is invalid, it should not contain uppercase characters.

**Comment by olidotjpeg** [comment]
This is a very important matter and should be fixed ASAP

**Comment by olidotjpeg** [comment]
#6 relates to this

**Comment by olidotjpeg** [comment]
@boserup THIS HAVE NOW BEEN SOLVED
