### ISSUE TITLE
use <?php instead of <?

### ISSUE THREAD

**Issue by mauran** [Unge-Programmoerer/Grubbe-framework#9]
I think we should support as many PHP configurations as possible. Per default shorthand `<?` isn't supported on most fresh PHP installations. We should probably change it to `<?php` instead. I would really like to hear your opinion about this, @kaspergrubbe.

**Comment by boserup** [comment]
We should update the readme to include installation and configuration instructions. It would then be appropriate to mention the requirement of enabling ```short_open_tag``` in php.ini.

**Comment by olidotjpeg** [comment]
Make a merge-request

**Comment by mauran** [comment]
I am going to make a 10/10 merge request

**Comment by Steiniche** [comment]
@mauran looking forward to it!

**Comment by onbjerg** [comment]
How do I make a merge request

**Comment by mauran** [comment]
Doing this takes an amount effort that I don't own. @onbjerg can you do this for me?
